//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeirellescPortfolio.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MeirellescPortfolio.Localization.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bio.
        /// </summary>
        public static string AppBar_Bio {
            get {
                return ResourceManager.GetString("AppBar_Bio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string AppBar_Contact {
            get {
                return ResourceManager.GetString("AppBar_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string AppBar_Home {
            get {
                return ResourceManager.GetString("AppBar_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Works.
        /// </summary>
        public static string AppBar_Works {
            get {
                return ResourceManager.GetString("AppBar_Works", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Main Character.
        /// </summary>
        public static string Bio_Header_Subtitle {
            get {
                return ResourceManager.GetString("Bio_Header_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bio.
        /// </summary>
        public static string Bio_Header_Title {
            get {
                return ResourceManager.GetString("Bio_Header_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s Team Up.
        /// </summary>
        public static string Contact_Header_Subtitle {
            get {
                return ResourceManager.GetString("Contact_Header_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact for Co-op.
        /// </summary>
        public static string Contact_Header_Title {
            get {
                return ResourceManager.GetString("Contact_Header_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2024 ALL RIGHTS RESERVED - LUCAS MEIRELLES.
        /// </summary>
        public static string Footer {
            get {
                return ResourceManager.GetString("Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOME.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leveling Up My Career.
        /// </summary>
        public static string Works_Header_Subtitle {
            get {
                return ResourceManager.GetString("Works_Header_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Works.
        /// </summary>
        public static string Works_Header_Title {
            get {
                return ResourceManager.GetString("Works_Header_Title", resourceCulture);
            }
        }
    }
}
